### ISSUE TITLE
Implement data retention in storage layer

### ISSUE THREAD

**Issue by petethepig** [pyroscope-io/pyroscope#168]
### Feature Description

Sometimes it doesn't make sense to store data indefinitely so we need to implement a way to do data retention. 

Internally Pyroscope uses segment trees to store the data. 
See our [Storage Design Doc](https://github.com/pyroscope-io/pyroscope/blob/main/docs/storage-design.md) for more context.

![Page2 3](https://user-images.githubusercontent.com/662636/116452030-192a1c80-a812-11eb-9489-dd2660d43e50.png)

We need to add a new retention threshold parameter that would control how much data (in days) can be stored in pyroscope. Then we would run some sort of a `Cleanup` method every once in a while to delete old data:

![Page3](https://user-images.githubusercontent.com/662636/116452984-2dbae480-a813-11eb-8c4a-f31808136182.png)

### TODO

* [x] Implement a method that would delete data before a certain time on [segment tree](https://github.com/pyroscope-io/pyroscope/blob/main/pkg/storage/segment/segment.go) and return a list of trees that need also need to be deleted.
* [ ] cover it with specs
* [x] add a retention option to [config](https://github.com/pyroscope-io/pyroscope/blob/main/pkg/config/config.go#L31)
* [ ] in storage package, put conditions in [Put method](https://github.com/pyroscope-io/pyroscope/blob/main/pkg/storage/storage.go#L180) that would prevent data ingestions past the retention threshold
* [ ] in storage package add a method that would delete segment tree nodes as well as relevant trees
* [ ] create a separate goroutine that would call this cleanup method every X minutes
