### ISSUE TITLE
Create Docs for deb and rpm repositories

### ISSUE THREAD

**Issue by petethepig** [pyroscope-io/pyroscope#171]
Currently we distribute pyroscope rpm and deb packages but we don't have repositories set up.

### TODO
* [x] set up rpm repos
* [x] set up deb repos
* [x] update release script to update the repos
* [x] put old packages in these repos
* [ ] update docs to reflect the changes

**Comment by eh-am** [comment]
They are all here https://pyroscope.io/downloads/
