### ISSUE TITLE
Automatically group nodes with similar names

### ISSUE THREAD

**Issue by petethepig** [pyroscope-io/pyroscope#258]
### Problem

There's this common issue where a program would generate function names dynamically, usually with a common prefix, e.g `conn_1234` or `html_slim_123123123123`. This generates a huge amount of extra nodes that should ideally be grouped into one.

So far we've seen it in 2 places:
* mongodb stacktraces (each connection is wrapped in a `conn_123` function)
* rails slim templates (see screenshot below)

![Pasted_Image_6_22_21__10_23_PM](https://user-images.githubusercontent.com/662636/123040445-9dc79000-d3a8-11eb-93e6-b13dec68dd49.png)

### Proposed solution

I think it's fair to assume that most functions would never call more than X other functions (let's say X = 50). Then we can assume that every node with > X children nodes is an example of this kind of issue. Maybe there's a way to detect these automatically. In that case we could replace all `conn_123` labels with something like `conn_*` or something like that. I wonder if there are some algorithms for finding common prefixes (common substrings). Either way, we need to find a way to detect these situations and ideally handle them automatically.

### TODO

* [ ] implement logic that would detect these situations
* [ ] implement logic that would fix these situations
* [ ] cover it with tests
