### ISSUE TITLE
"Failed to open process - check if it is running" error with Python on macOS

### ISSUE THREAD

**Issue by petethepig** [pyroscope-io/pyroscope#48]
### Community Call To Action

If you've experienced this, please post some details about your setup, e.g macOS version, python version, how you installed python on your machine, where it's installed, if you use pipenv / virtualenv or not in this issue.

### Summary

Some people report getting a message like this when they run `pyroscope exec` on macOS with python apps:
```
Failed to open process - check if it is running
```

Simplest way to reproduce:
```
sudo pyroscope exec -log-level debug python -c 'import time; time.sleep(10)'
```

### Context

Behind the scenes we're using this awesome piece of software called [py-spy](https://github.com/benfred/py-spy). There are some limitations that are described in the README of that project, e.g [here](https://github.com/benfred/py-spy#why-am-i-having-issues-profiling-usrbinpython-on-osx). For example, it straight up doesn't work with python that comes with macOS. Some of our users are reporting that sometimes it doesn't work even with python that's not preinstalled.

#### Relevant py-spy issues

* https://github.com/benfred/py-spy#why-am-i-having-issues-profiling-usrbinpython-on-osx
* https://github.com/benfred/py-spy/issues/242

### TODO:

* [x] collect more feedback from the community, try to understand all the cases when this happens
* [x] figure out how we can address some of these issues
* [x] for cases that we can fix we should develop solutions and also try to push them upstream where applicable
* [x] for cases that we can not fix / control for (e.g system integrity protection on macOS) add detection mechanisms and explicit messages in our software so that people don't waste time debugging this.

**Comment by JonathanRaiman** [comment]
Using Mac OSX 10.15.6, Python 3.8.2, installed python with OS I believe, installed in /usr/bin/python3. not using virtualenv

**Comment by LidiyaNorman** [comment]
Hi I'm having the same issue:

Using Mac OS Catalina 10.15.7, Python 3.7.7, installed python with OS, using virtualenv

**Comment by Rperry2174** [comment]
This should be fixed now with new pip package
